# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app-chart.fullname" . }}
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
